# Generated by Django 5.0.6 on 2024-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
